#!/bin/bash
# Credits to:
# adishourya, & rxyhn
# https://github.com/adishourya/wayland_dotfiles/blob/master/my_bar/scripts/workspace
# https://github.com/rxyhn/tokyo/blob/main/config/eww/bar/scripts/workspace

#define icons for workspaces 1-9
ic01=()
ic02=()
ic03=()
ic04=()
ic05=()
ic06=()
ic07=()
ic08=()

#initial check for occupied workspaces
for num in $(hyprctl workspaces | grep ID | sed 's/()/(1)/g' | awk 'NR>1{print $1}' RS='(' FS=')'); do 
		export o"$num"="$num"
done
 
#initial check for focused workspace
for num in $(hyprctl monitors | grep active | sed 's/()/(1)/g' | awk 'NR>1{print $1}' RS='(' FS=')'); do 
		export f"$num"="$num"
		export fnum=f"$num"
done

workspaces() {
		if [[ ${1:0:9} == "workspace" ]]; then #set focused workspace
				unset -v "$fnum"
				num=${1:11}
				export f"$num"="$num"
				export fnum=f"$num"

		elif [[ ${1:0:15} == "createworkspace" ]]; then #set Occupied workspace
				num=${1:17}
				export o"$num"="$num"
				export f"$num"="$num"
				
		elif [[ ${1:0:16} == "destroyworkspace" ]]; then #unset unoccupied workspace
				num=${1:18}
				unset -v o"$num" f"$num"
		fi

		#output eww widget
		echo 	"(eventbox :onscroll \"echo {} | sed -e 's/up/-1/g' -e 's/down/+1/g' | xargs hyprctl dispatch workspace\" \
       		   (box	:class \"works\"	:orientation \"v\" :halign \"center\"	:valign \"start\"	 :space-evenly \"false\" :spacing \"-5\" 	\
          	 (button :onclick \"hyprctl dispatch workspace 1\" :onrightclick \"hyprctl dispatch workspace 1\" :class \"0$o1$f1\" \"${ic01}\") \
          	 (button :onclick \"hyprctl dispatch workspace 2\" :onrightclick \"hyprctl dispatch workspace 2\"	:class \"0$o2$f2\" \"${ic02}\") \
             (button :onclick \"hyprctl dispatch workspace 3\" :onrightclick \"hyprctl dispatch workspace 3\"	:class \"0$o3$f3\" \"${ic03}\") \
        		 (button :onclick \"hyprctl dispatch workspace 4\" :onrightclick \"hyprctl dispatch workspace 4\"	:class \"0$o4$f4\" \"${ic04}\") \
             (button :onclick \"hyprctl dispatch workspace 5\" :onrightclick \"hyprctl dispatch workspace 5\"	:class \"0$o5$f5\" \"${ic05}\") \
      			 (button :onclick \"hyprctl dispatch workspace 6\" :onrightclick \"hyprctl dispatch workspace 6\"	:class \"0$o6$f6\" \"${ic06}\") \
             (button :onclick \"hyprctl dispatch workspace 7\" :onrightclick \"hyprctl dispatch workspace 7\"	:class \"0$o7$f7\" \"${ic07}\") \
						 (button :onclick \"hyprctl dispatch workspace 8\" :onrightclick \"hyprctl dispatch workspace 8\"	:class \"0$o8$f8\" \"${ic08}\") \
						 )\
        )"
}

workspaces

socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r event; do 
		workspaces "$event"
done
