#! /bin/sh
# Remember to make this file exucuteable: ("chmod +x bspwmrc")

# Launch sxhkd? Check '$HOME/.config/sxhkd/sxhkdrc' for more info!
pgrep -x sxhkd > /dev/null || sxhkd &

# Launch Polybar (if you want Polybar):
$HOME/.config/polybar/launch.sh

# Install Feh for USE of Wallpaper, the add your wallpaper path:
# Example: feh --bg-fill --randomize $HOME/stuff/pictures/wallpapers/* & 
feh --bg-fill /usr/share/backgrounds/fedora-workstation/winter-in-bohemia.png*

# Picom Startup (or add to .bashrc):
picom --daemon

# Workspaces:
bspc monitor -d I II III IV V VI VII

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Window Colors:
bspc config normal_border_color "#44475a"
bspc config active_border_color "#6272a4"
bspc config focused_border_color "#8be9fd"
bspc config presel_feedback_color "#6272a4"
