#+TITLE: BSPWM the One that Started it All
* Warning
Most of this code has not been touched nor updated in a long while (September 4, 2022) so beware if you decide to use this config or base your own out of it.

* Note
Bspwm was my 2nd window manager but my 1st where I felt like I could configure it (my 1st was i3wm). So Ill admit that mose likely most of this configuration isnt anything too special but I will mainly keep this saved for myself in case Ill ever need it again.

* Old README:
* Remember
Remember to read the comments they should all explain everything if you want to yoink some files from this repo! Also create a directory labeled 'polybar' in your '~/.config/' and put the .sh launch script in the 'polybar' directory. Remeber to set the bar name in the .sh script (piratebar)!

https://github.com/polybar/polybar/wiki

* Install.sh
You can now use my "install.sh"! This will do all the work for you, instead of manually inserting all the of files into the correct areas of your system!
How to use:

#+BEGIN_SRC sh
git clone https://github.com/DarthYoshi07/bspwm-config.git
#+END_SRC
#+BEGIN_SRC sh
cd ~/bspwm-config/
#+END_SRC
#+BEGIN_SRC sh
chmod +x install.sh
#+END_SRC
#+BEGIN_SRC sh
./install.sh
#+END_SRC
