* Dotfiles:
These are my currently used dotfiles containg many files for Xmonad + Emacs.

** Todo List and Updates:
Todo:
- [ ] Updated Emacs Config;
- [ ] Rewrite Emacs Config in Org;
- [ ] Learn + Configure EXWM;
- [X] Updated Xmonad Config;
- [ ] Rewrite Xmonad Config in Org;
- [X] Updated NixOS Config (I no longer use NixOS so it will no longer be *updated*);

(Personal Projects)
- [ ] Rewrite TheTuss bot in Rust;
- [ ] Finish the Buisness & Marketing Game using Bevy;
--------------------------------------------------------
** My Random Views and Other: 
- *Distro of choice:*
My currently used and distro of choice (for now) is Debian. My current Debian experience has been
great and I have the choice of getting frequently updated by using the Testing branch.
- *Window Manager of choice:*
As you can tell the main window manager I use is XMonad and its been great. Lots of options to
choose from by messing around with the contrib and it has been able to do everything I'd like
it to. The XMobar bar for XMonad is also *REALLY* good but I just hate the syntax of it's configuration.
