* Dotfiles:
These are my currently used dotfiles containg many files for Xmonad + Emacs.

** Todo List and Updates:
Todo:
- [...] Restructure Repo and add more README documentation
- [...] Learn + Configure EXWM;
- [...] Write Xmonad Config in Org;
- [...] Write Suckless' Configs in Org;
- [?] Rewrie NixOS Configuration?

(Personal Projects)
- [?] Rewrite TheTuss bot in another language;
- [?] Finish the Buisness & Marketing Game using Bevy;
--------------------------------------------------------
** My Personal Views: 
- *Distro of choice:*
Gentoo
- *Window Manager of choice:*
Suckless' DWM
- *The Coding Experience:*
A year ago my computer self destructed and could no longer boot into windows which made me dabble with
linux systems. It has been a key part of my learning experience with tech. If that would have never happened
I would have never faced the horros of my Ubuntu installation dying or the joys of installing Arch after 7 hours 
& the biggest part of installing Gentoo after a three day process. After a while of messing around with Linux systems
I wanted to learn how to create my own applications and video games which is still the stage I'm going through as of now.
I started off hoping to use the Unity engine and learning basic C# to trying to use Rust to create my projects.
- *Linux Tip:*
A big personal view of mine is that Operating Systems shouldn't be reccommended randomly to people and don't
force people to switch their system. They will hate it even more as they have no idea what they are doing with it. 
