#+title: TLP's Hyprland Configuration (+ Waybar)
* Introduction
Hyprland is a wayland compositor which has great speed & performace, while looking great. Default features include animations, dwindle + master layouts,
transparency...

I mainly just wanted to switch to Wayland and have been wanting to try out Hyprland so then I did! I have no regrets and little criticism.

* Configuration
** Hyprland
*** Startup
**** HyprStart
I have a command which starts up Hyprland acting like a substitute to Xorg's xinit. I have called this command "HyprStart", and placed it under
.local/bin which acts like usr/bin but for your user, this will not work unless ~/.local/bin is in your *$PATH*!
#+begin_src sh :tangle ~/.local/bin/HyprStart

#!/bin/sh
cd ~/

export HYPRLAND_LOG_WLR=1
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export SDL_IM_MODULE=fctitx
export GLFW_IM_MODULE=ibus

dunst &
emacs --daemon &

gsettings set org.gnome.desktop.interface gtk-theme "Nordic"
gsettings set org.gnome.desktop.wm.preferences theme "Nordic"

exec Hyprland
#+end_src
**** Inputs & Wallpaper
First I define the monitors, then I set variables with certain commands $setWallpaper uses swaybg to set Hyprland's wallpaper, then exec-once shall
execute that command, including waybar.

After that the input function takes in the US keyboard, I disabled follow_mouse as I personally hate it when activeness between windows is focused using the mouse.
The touchpad has tap to click enabled as my personal machine is a laptop.
The main important thing about the general function is that I have set the layout to be "Master".
#+begin_src sh :tangle ~/.config/hypr/hyprland.conf
monitor=,preferred,auto,auto

$bar0 = waybar -c ~/.config/waybar/config
$bar1 = waybar -c ~/.config/hypr/waybar/config
$setWallpaper0 = swaybg -i ~/.config/hypr/wallpapers/20XX.jpg &
$setWallpaper1 = swaybg -i ~/.config/hypr/wallpapers/totoro.png &

exec-once = $bar0 & $setWallpaper1

input {
    kb_layout = us
    kb_variant =
    kb_model =
    kb_options =
    kb_rules =
    follow_mouse = 0
    touchpad {
        natural_scroll = yes
        tap-to-click = true
    }
    sensitivity = 0
}

# Nord Colors:
$nord0 = 4C566A
$nord01 = 2E3440

general {
    gaps_in = 8 # 5
    gaps_out = 15 # 13
    border_size = 3 # 2
    col.active_border=0xfff5c2e7
    col.inactive_border=0xff45475a
    apply_sens_to_raw=0 # whether to apply the sensitivity to raw input (e.g. used by games where you aim using your mouse)
    col.group_border=0xff89dceb
    col.group_border_active=0xfff9e2af
    layout = master
}
#+end_src
*** Visual
I have very basic default window decorations & animations lots of this is just the default or close-to the default.
#+begin_src sh :tangle ~/.config/hypr/hyprland.conf
decoration {
    rounding = 15
    blur = yes
    blur_size = 3 # 3
    blur_passes = 1
    blur_new_optimizations = on
    drop_shadow = yes
    shadow_range = 4
    shadow_render_power = 3
    col.shadow = rgba(1a1a1aee)

    windowrule = opacity .9 0.8,^(Emacs)$
    windowrule = opacity .9 0.8,^(Alacritty)$
    windowrule = opacity .9 0.8,^(Spotify)$
    windowrule = tile, title:^(Spotify)$
}

animations {
    enabled = yes

    bezier = lrBezier, 0.05, 0.9, 0.1, 1.05
    bezier = udBezier,0.13,0.99,0.29,1.1

    # Up and Down Animations
    animation=windows,1,4,udBezier,slide
    animation=border,1,10,default
    animation=fade,1,10,default
    animation=workspaces,1,6,udBezier,slidevert
    # Left and Right Animations
    #animation=windows,0,7,lrBezier
    #animation=windowsOut,0,7,default,popin 80%
    #animation=border,0,10,default
    #animation=fade,0,7,default
    #animation=workspaces,0,6, default
}
#+end_src
*** Layouts & Extra
Default dwindle layout settings and tinkered Master layout.
#+begin_src sh :tangle ~/.config/hypr/hyprland.conf
dwindle {
    pseudotile = yes
    preserve_split = yes
}

master {
    new_is_master = false
    new_on_top = true
}

gestures {
    workspace_swipe = off
}
device:epic mouse V1 {
    sensitivity = -0.5
}
#+end_src
*** Keybinds & Variables
**** Variables
I like to predefine things like my terminal just in case if it changes I won't have to change the name in many locations.
Having for variables for volume and birghtness just makes things a lot easier.
#+begin_src sh :tangle ~/.config/hypr/hyprland.conf
$volUp          = amixer set Master 2%+
$volDown        = amixer set Master 2%-
$muteAudio      = amixer set Master toggle
$brightnessUp   = brightnessctl set +200
$brightnessDown = brightnessctl set 200-

$webcmd         = brave
$termcmd        = alacritty
$playercmd      = spotify
$screenshit     = Wayshot -s

$mod        = SUPER
$modShift   = SUPER SHIFT
$meta       = ALT
$metaShift  = ALT SHIFT
#+end_src
**** FN Key-Bindings
For laptop use here are some bindings for those top FN Keys.
#+begin_src sh :tangle ~/.config/hypr/hyprland.conf
binde   = , XF86AudioRaiseVolume, exec, $volUp
binde   = , XF86AudioLowerVolume, exec, $volDown
bindr   = , XF86AudioMute, exec, $muteAudio
bind    = , XF86AudioPlay, exec, playerctl play-pause
bind    = , XF86AudioNext, exec, playerctl next
bind    = , XF86AudioPrev, exec, playerctl previous
binde   = , XF86MonBrightnessUp, exec, $brightnessUp
binde   = , XF86MonBrightnessDown, exec, $brightnessDown
bind    = , SunPrint_Screen, exec, $screenshit
bind    = , XF86Search, exec, wofi -S drun -G -I -m -t
bind    = , f7, exec, $termcmd
#+end_src
**** Window Management & Keybinds
Hyprland provides two kinds of layouts, being "Master", & "Dwindle". Dwindle by default is highly mouse based and I prefer having my windows
in a set layout by all times.
***** Simple Bindings
#+begin_src sh :tangle ~/.config/hypr/hyprland.conf
bind  = $modShift, Q, exit,
binde = $mod, W, killactive,
bind  = $mod, RETURN, exec, $termcmd
#+end_src
***** Submaps/Keychords
Here will be "submaps/keychords" for my hyprland config, the first one listed can resize windows from their set range.
****** Leader Submap
The "Leader" Submap is the submap where most keychords will be stored, the main way to acess these chords is by doing MOD+SPACE.
#+begin_src sh :tangle ~/.config/hypr/hyprland.conf
bind    = $mod, SPACE, submap, leader
submap  = leader

bind    = , RETURN, exec, $termcmd
binde   = , F, exec, wofi -S run -G -I -m -t
bind    = , B, exec, $webcmd
bind    = , S, exec, $playercmd
bind    = , E, exec, emacsclient -c
bind    = , D, exec, discord

bind    = , SPACE, submap, reset
submap  = reset
#+end_src
****** Window Management Submap
This submap has bindings all about window management using the Master layout.
Honestly using this submap would be faster than moving your finger and constantly holding down the MOD key.
#+begin_src sh :tangle ~/.config/hypr/hyprland.conf
bind    = $mod, f, submap, master
submap  = master

bind    = , RETURN, layoutmsg, swapwithmaster
binde   = SHIFT, L, layoutmsg, swapnext
binde   = SHIFT, H, layoutmsg, swapprev
binde   = SHIFT, J, layoutmsg, swapnext
binde   = SHIFT, K, layoutmsg, swapprev

binde   = , H, movefocus, l
binde   = , L, movefocus, r
binde   = , K, movefocus, u
binde   = , J, movefocus, d
binde   = , W, killactive,

bind    = , SPACE, togglefloating,
bind    = , I, layoutmsg, addmaster
bind    = , O, layoutmsg, removemaster
bindr   = , U, layoutmsg, orientationtop
bindr   = , P, layoutmsg, orientationbottom

bindr   = , T, layoutmsg, orientationleft
bind    = , R, submap, resize

bind    = , f, submap, reset
submap  = reset
#+end_src
****** Resize Window Function
#+begin_src sh :tangle ~/.config/hypr/hyprland.conf
bind    = $mod, R, submap, resize
submap  = resize

binde   =, L, resizeactive, 10 0
binde   =, H, resizeactive, -10 0
binde   =, K, resizeactive,0 -10
binde   =, J, resizeactive, 0 10

bind    =, R, submap, reset
submap  = reset
#+end_src
**** Tags/Workspaces
Default workspaces config.
#+begin_src sh :tangle ~/.config/hypr/hyprland.conf
bind = $mod, 1, workspace, 1
bind = $mod, 2, workspace, 2
bind = $mod, 3, workspace, 3
bind = $mod, 4, workspace, 4
bind = $mod, 5, workspace, 5
bind = $mod, 6, workspace, 6
bind = $mod, 7, workspace, 7
bind = $mod, 8, workspace, 8
bind = $mod, 9, workspace, 9
bind = $mod, 0, workspace, 10

bind = $modShift, 1, movetoworkspace, 1
bind = $modShift, 2, movetoworkspace, 2
bind = $modShift, 3, movetoworkspace, 3
bind = $modShift, 4, movetoworkspace, 4
bind = $modShift, 5, movetoworkspace, 5
bind = $modShift, 6, movetoworkspace, 6
bind = $modShift, 7, movetoworkspace, 7
bind = $modShift, 8, movetoworkspace, 8
bind = $modShift, 9, movetoworkspace, 9
bind = $modShift, 0, movetoworkspace, 10

bind = $mod, mouse_down, workspace, e+1
bind = $mod, mouse_up, workspace, e-1

bindm = $mod, mouse:272, movewindow
bindm = $mod, mouse:273, resizewindow
#+end_src
** Waybars
*** Custom Bar I;
**** Config
Custom Modules which indicate arrows for design choice, audio mod, clock mods, cpu & ram mods, battery mod, and my personal favroite mod: Spotify.
#+begin_src json :tangle ~/.config/waybar/config
// -*- mode: json -*-

{
	"layer": "top",
	"position": "top",

	"modules-left": [
        "custom/right-arrow-dark",
	    "custom/right-arrow-light",
	    "pulseaudio",
	    "custom/right-arrow-dark",
    ],
	"modules-center": [
	    "custom/left-arrow-dark",
		"clock#1",
		"custom/left-arrow-light",
		"custom/left-arrow-dark",
		"clock#2",
		"custom/right-arrow-dark",
		"custom/right-arrow-light",
		"clock#3",
		"custom/right-arrow-dark"
	],
	"modules-right": [
	    "custom/left-arrow-dark",
	    "memory",
	    "custom/left-arrow-light",
	    "custom/left-arrow-dark",

	    "cpu",

	    "custom/right-arrow-dark",
	    "custom/right-arrow-light",
	    "battery",
	    "custom/left-arrow-light",
	    "custom/left-arrow-dark",
	],

    // Style:
	"custom/left-arrow-dark": {
		"format": "",
		"tooltip": false
	},
	"custom/left-arrow-light": {
		"format": "",
		"tooltip": false
	},
	"custom/right-arrow-dark": {
		"format": "",
		"tooltip": false
	},
	"custom/right-arrow-light": {
		"format": "",
		"tooltip": false
	},

    // Moudles:
    "bluetooth": {
	    "format": " {status}",
	    "format-connected": " {num_connections} connected",
	    "tooltip-format": "{controller_alias}\t{controller_address}",
	    "tooltip-format-connected": "{controller_alias}\t{controller_address}\n\n{device_enumerate}",
	    "tooltip-format-enumerate-connected": "{device_alias}\t{device_address}",
        "on-click": "alacritty -e bluetuith",
    },
    "custom/spicetify": {
        "exec": "/usr/bin/python3 $HOME/.config/waybar/custom/mediaplayer.py --player spotify",
    	   "format": "{}  ",
    	   "return-type": "json",
    	   "on-click": "playerctl play-pause",
    	   "on-scroll-up": "playerctl next",
    	   "on-scroll-down": "playerctl previous",
	},
	"pulseaudio": {
	    "format": "{volume}% {icon}",
    	    "format-bluetooth": "{volume}% {icon}",
    	    "format-muted": "",
    	    "format-icons": {
            		    "headphone": "",
        		    "hands-free": "",
        		    "headset": "",
        		    "phone": "",
        		    "portable": "",
        		    "car": "",
        		    "default": ["", ""],
    			    },
    	   "scroll-step": 1,
    	   "on-click": "pavucontrol",
    	   "ignored-sinks": ["Easy Effects Sink"],
	},

	"clock#1": {
		"format": "{:%A}",
		"tooltip": false
	},
	"clock#2": {
		"format": "{:%I:%M:%p}",
		"tooltip": false
	},
	"clock#3": {
		"format": "{:%m-%d}",
		"tooltip": false
	},
	"memory": {
		"interval": 5,
		"format": "Mem {}%",
		"on-click": "alacritty -e htop"
	},
	"cpu": {
		"interval": 5,
		"format": "CPU {usage:2}%",
		"on-click": "alacritty -e htop"
	},
	"battery": {
		"states": {
			"good": 95,
			"warning": 30,
			"critical": 15
		},
		"format": "{icon} {capacity}%",
		"format-icons": [
			"",
			"",
			"",
			"",
			""
		]
	},
}
#+end_src
**** Style.css
#+begin_src css :tangle ~/.config/waybar/style.css
 ,* {
    /* `otf-font-awesome` is required to be installed for icons */
    font-family: monospace;
    font-size: 15px;
}

window#waybar {
        background: #3B4252;
	    color: #3B4252;
}

#window {
    border-radius: 20px;
    padding-left: 10px;
    padding-right: 10px;
}

#custom-right-arrow-dark,
#custom-left-arrow-dark {
	color: #2E3440;
}
#custom-right-arrow-light,
#custom-left-arrow-light {
	color: #3B4252;
	background: #2E3440;
}

#clock,
#battery,
#cpu,
#memory,
#pulseaudio,
#bluetooth
#custom-modules,
#custom-media {
    background: #2E3440;
}

.custom-spotify {
    padding: 0 5px;
    margin: 0 0px;
    background: #2E3440;
    color: #5E81AC;
}

#clock {
    color: #BF616A;
}

#battery {
    color: #A3BE8C;
}

#battery.charging, #battery.plugged {
    color: #88C0D0;
}

@keyframes blink {
    to {
        color: #D08770;
    }
}

#battery.critical:not(.charging) {
    color: #BF616A;
    animation-name: blink;
    animation-duration: 0.5s;
    animation-timing-function: linear;
    animation-iteration-count: infinite;
    animation-direction: alternate;
}

#cpu {
    color: #EBCB8B;
}

#memory {
    color: #B48EAD;
}

#pulseaudio {
    color: #A3BE8C;
}

#pulseaudio.muted {
    color: #3B4252;
}

#bluetooth {
    color: #EBCB8B;
}

#bluetooth.disabled {
    color: #BF616A;
}
#bluetooth.connected {
    color: #EBCB8B;
}
#bluetooth.pairable {
    color: #A3BE8C;
}
#+end_src
*** Custom Bar II;
**** Config
#+begin_src json :tangle ~/.config/hypr/waybar/config
// -*- mode: json -*-
 {
	"layer": "top",
	"modules-left": ["sway/workspaces", "mpd", "sway/mode"],
	"modules-center": [],
	"modules-right": ["network", "pulseaudio", "temperature", "cpu", "memory", "clock"],
	"mpd": {
		"tooltip": false,
		"format": "{stateIcon} {artist} - {album} - {title} ({elapsedTime:%M:%S}/{totalTime:%M:%S})",
		"format-disconnected": "ﳌ",
		"format-stopped": "",
        "state-icons": {
            "playing": "",
            "paused": ""
        }
	},
	"pulseaudio": {
		"tooltip": false,
		"scroll-step": 5,
		"format": "{icon} {volume}%",
		"format-icons": {
			"default": ["奄", "奔", "墳"]
		}
	},
	"network": {
		"tooltip": false,
		"format-wifi": " {essid} {ipaddr}",
		"format-ethernet": " {ipaddr}"
	},
	"cpu": {
		"tooltip": false,
		"format": " {}%"
	},
	"memory": {
		"tooltip": false,
		"format": " {}%"
	}
}
#+end_src
**** Style.css
#+begin_src css :tangle ~/.config/hypr/waybar/style.css
 * {
	border: none;
	border-radius: 0;
	font-family: Nerd Font Hack;
	font-size: 14px;
	min-height: 24px;
}

window#waybar {
	background: transparent;
}

window#waybar.hidden {
	opacity: 0.2;
}

#window {
    margin-top: 8px;
    padding-left: 16px;
    padding-right: 16px;
	border-radius: 26px;
	transition: none;
	/*
    color: #f8f8f2;
	background: #282a36;
    */
    color: transparent;
	background: transparent;
}

window#waybar.termite #window,
window#waybar.Firefox #window,
window#waybar.Navigator #window,
window#waybar.PCSX2 #window {
    color: #4d4d4d;
	background: #e6e6e6;
}

#workspaces {
	margin-top: 8px;
	margin-left: 12px;
	margin-bottom: 0;
	border-radius: 26px;
	background: #282a36;
	transition: none;
}

#workspaces button {
	transition: none;
	color: #f8f8f2;
	background: transparent;
	font-size: 16px;
}

#workspaces button.focused {
	color: #9aedfe;
}

#workspaces button:hover {
	transition: none;
	box-shadow: inherit;
	text-shadow: inherit;
	color: #ff79c6;
}

#mpd {
	margin-top: 8px;
	margin-left: 8px;
	padding-left: 16px;
	padding-right: 16px;
	margin-bottom: 0;
	border-radius: 26px;
	background: #282a36;
	transition: none;
	color: #4d4d4d;
	background: #5af78e;
}

#mpd.disconnected,
#mpd.stopped {
	color: #f8f8f2;
	background: #282a36;
}

#network {
	margin-top: 8px;
	margin-left: 8px;
	padding-left: 16px;
	padding-right: 16px;
	margin-bottom: 0;
	border-radius: 26px;
	transition: none;
	color: #4d4d4d;
	background: #bd93f9;
}

#pulseaudio {
	margin-top: 8px;
	margin-left: 8px;
	padding-left: 16px;
	padding-right: 16px;
	margin-bottom: 0;
	border-radius: 26px;
	transition: none;
	color: #4d4d4d;
	background: #9aedfe;
}

#temperature {
	margin-top: 8px;
	margin-left: 8px;
	padding-left: 16px;
	padding-right: 16px;
	margin-bottom: 0;
	border-radius: 26px;
	transition: none;
	color: #4d4d4d;
	background: #5af78e;
}

#cpu {
	margin-top: 8px;
	margin-left: 8px;
	padding-left: 16px;
	padding-right: 16px;
	margin-bottom: 0;
	border-radius: 26px;
	transition: none;
	color: #4d4d4d;
	background: #f1fa8c;
}

#memory {
	margin-top: 8px;
	margin-left: 8px;
	padding-left: 16px;
	padding-right: 16px;
	margin-bottom: 0;
	border-radius: 26px;
	transition: none;
	color: #4d4d4d;
	background: #ff6e67;
}

#clock {
	margin-top: 8px;
	margin-left: 8px;
	margin-right: 12px;
	padding-left: 16px;
	padding-right: 16px;
	margin-bottom: 0;
	border-radius: 26px;
	transition: none;
	color: #f8f8f2;
	background: #282a36;
}

#+end_src
