#!/bin/sh
export SCRIPTPATH
SCRIPTPATH="$( cd "$(dirname "$0")" || exit; pwd -P )"

# Down the last running theme
if [ -f "/tmp/leftwm-theme-down" ]; then
    /tmp/leftwm-theme-down
    rm /tmp/leftwm-theme-down
fi
ln -s "$SCRIPTPATH"/down /tmp/leftwm-theme-down

# Set the theme.toml config
leftwm command "LoadTheme $SCRIPTPATH/theme.ron"

# Set Background & Daemons
feh --bg-fill "$SCRIPTPATH"/wallpapers/background.jpg

picom &
dunst &
polybar &
