(require 'package)
(add-to-list 'package-archives '("melpa" .  "https://melpa.org/packages/") t) 
(add-to-list 'package-archives '("elpa" . "https://elpa.gnu.org/packages/") t) 
(add-to-list 'package-archives '("org" . "https://orgmode.org/elpa/") t) 
(package-initialize)
(package-refresh-contents)
