#+TITLE: GNU Emacs TreeHouse Configuration

* Welcome Mat
This is my personal Emacs configuration and I call it the "GNU Emacs TreeHouse" or just "Emacs TreeHouse" for short.
The "Emacs Treehouse" (refered as the "treehouse") is a personal attempt of creating an IDE-like editor and personal text editor
for just text editing reasons.

Things included (or WILL be included) are:
- [X] Full Org-Mode Configuration
- [?] LSP Support (soon)
- [X] Tree-Sitter
- [X] Rust-Mode
- [X] Haskell-Mode
- [X] Python-Mode
- [X] Go-Mode
- [X] Desktop-like Configuration

and more.
This whole configuration (like many of my dotfiles) are written into Org-Mode so it can read better, so I can add explanations to my code,
and just beacuse it organizes things a lot better for me.

* The Code
The code is seperated into sections (like a treehouse):

- The Sky       ; Extra Information about the Configuration
- The TreeHouse ; Exwm 
- The Tree      ; init.el
- The Dirt      ; Package Configurations
- The Roots     ; package.el
